<a href="https://colab.research.google.com/github/Shahnilsharma/Learning-Numerical-and-Symbolic-Computing/blob/main/Basics_Numpy_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This task demonstrates basic operations using the NumPy library in Python. Two arrays, `x` and `y`, are defined with integer elements. The code performs element-wise addition and multiplication of these arrays, showcasing NumPy's ability to handle arithmetic operations efficiently. Additionally, it computes the square root of each element in array `x` using the `np.sqrt` function. The outputs illustrate fundamental vectorized operations common in numerical computing.

In [ ]:
import numpy as np
x= np.array([10,20,30]);
y=np.array([1,2,3])

print("Addition", x+y)
print("Multiplication",x*y)
print("square root", np.sqrt(x))

Addition [11 22 33]
Multiplication [10 40 90]
square root [3.16227766 4.47213595 5.47722558]


In this task, the NumPy library was utilized to create and display one-dimensional and two-dimensional arrays. Initially, a one-dimensional array containing five integer elements was generated and printed. Subsequently, a two-dimensional array, structured as a 2x2 matrix, was created and displayed. This exercise demonstrates the fundamental array creation and printing capabilities provided by the NumPy library in Python.



In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("1D Array:", a)
b = np.array([[1, 2], [3, 4]])
print("2D Array:\n", b)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2]
 [3 4]]


In this task, a two-dimensional NumPy array was created with the elements [, [4,The code then retrieves and prints three important attributes of the array: its shape, which indicates the array's dimensions (number of rows and columns); its size, representing the total number of elements in the array; and its data type, specifying the type of elements stored within the array. This exercise showcases basic inspection methods for understanding the structure and properties of NumPy arrays.


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("shape ", arr.shape)
print("size",arr.size)
print("type", arr.dtype)

shape  (2, 3)
size 6
type int64


In this task, a one-dimensional NumPy array containing integers from 1 to 10 was created using the arange function. The array was then reshaped into a two-dimensional array with 2 rows and 5 columns using the reshape method. The reshaped array was printed, followed by printing its flattened version, which converts the two-dimensional array back into a one-dimensional array using the flatten method. This exercise demonstrates array creation, reshaping, and flattening techniques in NumPy to manipulate array dimensions effectively.

In [ ]:
import numpy as np

a = np.arange(1,11)
b = a.reshape((2,5))

print("reshaped:\n",b)
print("flattened:",b.flatten())

reshaped:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
flattened: [ 1  2  3  4  5  6  7  8  9 10]


In this task, several specialized NumPy arrays were created and displayed to demonstrate different initialization methods. A 2x2 array of zeros was created using the zeros function, followed by a 2x2 array of ones generated with the ones function. Additionally, an identity matrix of size 3x3 was created using the eye function. These arrays were then printed to illustrate the various ways NumPy can be used to initialize arrays with specific values or structures commonly used in numerical computing.a

In [ ]:
import numpy as np
zeros=np.zeros((2,2))
ones=np.ones((2,2))
identify = np.eye(3)
print("zeros:\n",zeros)
print("ones:\n",ones)
print("identify: \n",identify)

zeros:
 [[0. 0.]
 [0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]]
identify: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In this task, a one-dimensional NumPy array containing five integer elements was created. The code computes and prints three key statistical measures of the array's data: the mean, which represents the average value; the maximum, indicating the largest element in the array; and the standard deviation, which quantifies the amount of variation or dispersion of the data. This exercise demonstrates how to perform basic statistical analysis on numerical data using NumPy functions.




In [ ]:
data = np.array([10,20,30,40,50])
print("mean",np.mean(data))
print("max",np.max(data))
print("standard deviation",np.std(data))

mean 30.0
max 50
standard deviation 14.142135623730951


This task covers fundamental NumPy operations including creating arrays, generating sequences, reshaping arrays, element-wise addition, matrix multiplication, and computing basic statistics. It highlights essential techniques for array manipulation and analysis in scientific computing.

In [ ]:
import numpy as np

# 1. Create a simple 1D array using np.array()
array_1d = np.array([1, 2, 3, 4, 5])
print("1. 1D Array:")
print(array_1d)

# 2. Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))
print("\n2. 3x3 Array of Zeros:")
print(zeros_array)

# 3. Create a 2x4 array of ones
ones_array = np.ones((2, 4))
print("\n3. 2x4 Array of Ones:")
print(ones_array)

# 4. Create a 4x4 identity matrix
identity_matrix = np.eye(4)
print("\n4. Identity Matrix (4x4):")
print(identity_matrix)

# 5. Create a range of numbers from 0 to 8 with a step of 2
range_array = np.arange(0, 10, 2)
print("\n5. Array using arange (0 to 8 step 2):")
print(range_array)

# 6. Create 5 evenly spaced numbers between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print("\n6. Evenly spaced values from 0 to 1 (linspace):")
print(linspace_array)

# 7. Reshape a 1D array into a 2D matrix
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape((2, 3))
print("\n7. Reshaped Array (2 rows, 3 columns):")
print(reshaped_array)

# 8. Perform element-wise addition
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
sum_array = a + b
print("\n8. Element-wise Addition:")
print(sum_array)

# 9. Matrix multiplication using dot product
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(mat1, mat2)
print("\n9. Matrix Multiplication (dot product):")
print(dot_product)

# 10. Find maximum, minimum, and mean of an array
sample_array = np.array([5, 10, 15, 20])
print("\n10. Array Stats (max, min, mean):")
print("Max:", np.max(sample_array))
print("Min:", np.min(sample_array))
print("Mean:", np.mean(sample_array))

1. 1D Array:
[1 2 3 4 5]

2. 3x3 Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3. 2x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

4. Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

5. Array using arange (0 to 8 step 2):
[0 2 4 6 8]

6. Evenly spaced values from 0 to 1 (linspace):
[0.   0.25 0.5  0.75 1.  ]

7. Reshaped Array (2 rows, 3 columns):
[[1 2 3]
 [4 5 6]]

8. Element-wise Addition:
[11 22 33]

9. Matrix Multiplication (dot product):
[[19 22]
 [43 50]]

10. Array Stats (max, min, mean):
Max: 20
Min: 5
Mean: 12.5
